### ISSUE TITLE
Mod crashes on dedicated server

### ISSUE THREAD

**Issue by EgbertMedia** [joe-vettek/Dynamic-Trees-for-FruitTrees#1]
Hey, the mod seems to work fine on singleplayer, but the mod crashes on a dedicated server

```
Failure message: Dynamic Trees for Fruitful Fun (dtfruitfulfun) has failed to load correctly
--
39 | java.lang.RuntimeException: Attempted to load class xueluoanping/dtfruitfulfun/client/BlockColorHandler for invalid dist DEDICATED_SERVER

<!--EndFragment-->
```
https://mclo.gs/S597o1O

**Comment by joe-vettek** [comment]
I'm in the process of refurbishing the datapack section, so a fix is expected to be released at a later date, sorry.  JourneyMap has been messing up my environment for the past few versions.

**Comment by EgbertMedia** [comment]
No problem! If there is anything I can do to help or test for you, let me know

**Comment by joe-vettek** [comment]
Thanks for the support, I actually uploaded it about a few hours ago. I was told that there is no need to write a recipe generator.
